services:
  # --- API (Node/Express) ---
  - type: web
    name: spectr-api
    runtime: node
    plan: free
    region: oregon
    repo: https://github.com/your/repo.git
    branch: main
    buildCommand: |
      npm ci
    startCommand: |
      node server.js
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: NODE_VERSION
        value: 18
      # Упростим CORS для MVP. Позже можно заменить на конкретный домен фронта.
      - key: ORIGIN
        value: "*"
      # HMAC для n8n (по желанию)
      - key: N8N_SECRET
        generateValue: true

  # --- Frontend (Vite React, статика) ---
  - type: web
    name: spectr-web
    runtime: static
    plan: free
    repo: https://github.com/your/repo.git
    branch: main
    buildCommand: |
      npm ci
      npm run build
    staticPublishPath: dist
    autoDeploy: true
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      # Передаём фронту ХОСТ API (без схемы/протокола):
      - key: VITE_API_HOST
        fromService:
          type: web
          name: spectr-api
          property: host
