services:
  # --- API (Node/Express) ---
  - type: web
    name: spectr-api
    runtime: node
    plan: starter
    region: oregon
    repo: https://github.com/your/repo.git
    buildCommand: |
      npm ci
    startCommand: |
      node server.js
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: ORIGIN
        value: "*"
      - key: N8N_SECRET
        generateValue: true

  # --- Frontend (Vite React, статика) ---
  - type: web
    name: spectr-web
    runtime: static
    plan: starter
    repo: https://github.com/your/repo.git
    buildCommand: |
      npm ci
      npm run build
    staticPublishPath: dist
    autoDeploy: true
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_HOST
        fromService:
          type: web
          name: spectr-api
          property: host
