services:
  # --- API (Node/Express) ---
  - type: web
    name: spectr-api
    runtime: node          # раньше было env: node — используем современное поле runtime
    plan: free             # поменяй на starter/standard при нагрузке
    region: oregon
    repo: https://github.com/your/repo.git
    branch: main
    buildCommand: |
      npm ci
    startCommand: |
      node server.js
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: NODE_VERSION
        value: 18
      # Разрешаем CORS с домена фронта (URL статического сайта на Render)
      - key: ORIGIN
        fromService:
          type: web
          name: spectr-web
          property: url
      # HMAC для n8n (опционально)
      - key: N8N_SECRET
        generateValue: true

  # --- Frontend (Vite React, статика на CDN Render) ---
  - type: web
    name: spectr-web
    runtime: static        # ключ для статических сайтов
    plan: free
    region: oregon
    repo: https://github.com/your/repo.git
    branch: main
    buildCommand: |
      npm ci
      npm run build
    staticPublishPath: dist
    autoDeploy: true
    # SPA rewrite, чтобы маршруты React не падали в 404
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      # Бэкенд для фронта: URL сервиса spectr-api
      - key: VITE_API_BASE
        fromService:
          type: web
          name: spectr-api
          property: url
